/**
 * SKMattermost
 * ShopKit Mattermost API
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import CloseEvents  from '../../src/api/CloseEvents';

describe('CloseApi', function(){
  let events;
  beforeEach(function() {
    events = new CloseEvents({
        registerEventListener(){
        },
        emitEvent(){
        }
    });

  });


    describe('closeRequested', function() {
        it('should emit event closeRequested successfully', (done)=> {
        //uncomment below and update the code to test closeRequested
        //register listener.
        //events.addCloseRequestedEventListener(()=>done());
        //emit event.
        //events.emitCloseRequested();
        //});
        done();
        });
    });

});
